apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: migration-docker-kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data
