apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: migration-docker-kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
