apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"web-service","namespace":"migration-docker-kubernetes"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":5000}],"selector":{"app":"web"}}}
  creationTimestamp: "2024-09-04T10:16:26Z"
  name: web-service
  namespace: migration-docker-kubernetes
  resourceVersion: "76727"
  uid: b9dc9ed0-cd24-4b88-bc78-f7a389a64c6a
spec:
  clusterIP: 10.109.76.236
  clusterIPs:
  - 10.109.76.236
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: web
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}